# what is an ""array""?
#### . An array is a data structure for storing and retrieving data

## Restrictions of numpy array
#### : All elements of the array must be of the same type of data.
#### :Once created, the total size of the array can't change

In [5]:
import numpy as np
a =np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>

In [1]:
import numpy as np
a =np.array([1,2,3,4,5,6])
a.ndim

1

In [3]:
new_array=np.array([123,3,334])
print(new_array)

[123   3 334]

In [8]:
new_array_1=np.array(['hellomohitboura',12,'mohitbouramohit'])
(new_array_1)
new_array_1.dtype

dtype('<U21')

In [44]:
new_array_1

array(['hellomohitboura', '12', 'mohitbouramohit'], dtype='<U21')

In [42]:
len('mohitbouramohit')

15

In [4]:
import numpy as np
a=np.array([123445667,'mohit'])
a[1]

np.str_('mohit')

In [4]:
len(123445667,'mohit')

TypeError: len() takes exactly one argument (2 given)

In [1]:
import numpy as np
a=np.array({12,3,4,5,5,6,6})
a[1]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [10]:
import numpy as np
a=np.array([1,2,3,4,5,5,'mohit boura'])
a

array(['1', '2', '3', '4', '5', '5', 'mohit boura'], dtype='<U21')

In [11]:
import numpy as np
a=np.array((1,1,3,4,5,6))
a

array([1, 1, 3, 4, 5, 6])

 ## index , slicing

In [2]:
import numpy as np
f=np.array([1,2,3,4])
f.ndim

1

In [3]:
f.size

4

In [4]:
f.shape

(4,)

In [5]:
f.dtype

dtype('int64')

In [4]:
import numpy as np
g=np.array([1,2,3,4,5])
g[::-1]

array([5, 4, 3, 2, 1])

In [10]:
import numpy as np
a=np.array([1,2,3,4,5,'mohit'])
a[1]

np.str_('2')

In [11]:
a[0:]

array(['1', '2', '3', '4', '5', 'mohit'], dtype='<U21')

In [12]:
a[2]=12
a

array(['1', '2', '12', '4', '5', 'mohit'], dtype='<U21')

In [11]:
import numpy as np
s=np.array([[1,2,3,4]
             ,[5,6,7,8]
             ,[1,2,3,4]])
s

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [12]:
s[1]

array([5, 6, 7, 8])

In [13]:
s.ndim

2

In [14]:
s[1,2]

np.int64(7)

### Another diffference between an array and a list of lists is that an elements of the array can be accesed by spcifying the index along each axis 
###  wthin a singel set of  squance brackets ,seprated by comments  ###

In [15]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
import numpy as np
q=np.array ([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
            
q.ndim

2

In [6]:
q[0]

array([1, 2, 3, 4])

In [7]:
q[1,0]

np.int64(5)

In [8]:
q[1,3]

np.int64(8)

In [9]:
q[1][2]

np.int64(7)

In [105]:
q[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## type casting

In [49]:
z=np.array([1,2,3,3,4,56,])
s=set(z)
s

{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(56)}

In [33]:
s.clear()

In [34]:
s

set()

In [35]:
import numpy as np
b=np.array([1,2,3,44,3,3,3])
a=set(b)
a

{np.int64(1), np.int64(2), np.int64(3), np.int64(44)}

In [36]:
a=set(b)
print(a)

{np.int64(1), np.int64(2), np.int64(3), np.int64(44)}

In [37]:
import numpy as np
s=np.array(['mohit boura','mohit boura'])
a=tuple(s)
print(a)

(np.str_('mohit boura'), np.str_('mohit boura'))

In [38]:
a=set(s)
a

{np.str_('mohit boura')}

In [39]:
import numpy as np
s=np.array ({'mohit','mohit'})
s

array({'mohit'}, dtype=object)

In [40]:
import numpy as mohit
s=mohit.array ({1,2,3,4,5,5,67,8,9})
s

array({1, 2, 3, 4, 5, 67, 8, 9}, dtype=object)

In [41]:
old_list=np.array([1,2,3,4,56,'mohit boura']) ## after type casting  use use list add(statement)!!
old_list
new_list=list(old_list)
new_list.append(['hello data'])
new_list

[np.str_('1'),
 np.str_('2'),
 np.str_('3'),
 np.str_('4'),
 np.str_('56'),
 np.str_('mohit boura'),
 ['hello data']]

In [42]:
a=np.array({12,3,4,4,5,6,6,7},[1,2,3,4,5,6,7,8])
a

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [2]:
import numpy as np
d=np.array ((1,2,2,2,3,4,5,6))
a=tuple(d)
a.count(2)

3

In [18]:
a=np.array([{12,3,4,4,5,6,6,7},{10,12,2,3,5,33,444,55,8,122,0}]) # two set in one array python remove duplicet items from each set. depand on this copy items.
a

array([{3, 4, 5, 6, 7, 12}, {0, 33, 2, 3, 5, 8, 10, 12, 55, 122, 444}],
      dtype=object)

# array attributes
### ndim: The number of dimensions an array is contained in the ndim attributes

In [4]:
a=np.array (23)
a.ndim

0

In [5]:
li=np.array([1,2,3,4])
li.ndim

1

In [6]:
nu=np.array([[{1,2,3,4,4,4,4,4}],[{1,2,3,3,4}]])
nu.ndim

2

In [7]:
num=np.array([[[1,2,3,4,5],[1,2,3,4,5],[2,3,4,5,6]]])
num1=np.array([[[1,2,4,4,5],[1,2,3,4,56],[12,2,3,4,55]]])
n=np.concatenate((num,num1),axis=2)
n.shape
n

array([[[ 1,  2,  3,  4,  5,  1,  2,  4,  4,  5],
        [ 1,  2,  3,  4,  5,  1,  2,  3,  4, 56],
        [ 2,  3,  4,  5,  6, 12,  2,  3,  4, 55]]])

In [2]:
import numpy as np
s=np.array([1,2,3,4])
d=np.array([5,6,7,8])
np.concatenate((s,d))

array([1, 2, 3, 4, 5, 6, 7, 8])

### shape: the shape of an array is a tuple of non-negative integers that specify the number of element along dimension

In [9]:
s=np.array([[1,2,3,4,-5],[1,2,3,4,5]])
s.shape

(2, 5)

### size : The fixed total number of elements in array  is comtained in the size attribute

In [89]:
c=np.array([[1,2,3,3,4],[1,2,3,4,5]])
c.size

10

## dtype : the data type of the elements of the  array can be checked using the dtype attribute.
## Note: the data type of all the elements of an numpy array is same that is homogeneous

In [91]:
c.dtype

dtype('int64')

In [93]:
str1=np.array(['mohit boura'])
str1.dtype

dtype('<U11')

# some other techniques to create an array 
## this section covers np.zeros() , np.ones(), np.empty (), np.arange(), np.linspace

## np.zeros  you can create an array filed with zeros

In [110]:
se=np.zeros(3)
print(se)

[0. 0. 0.]

In [121]:
# create a table of zeros (2 rows and 3 columns)
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.ones You can creat an array filed with ones

In [122]:
one_array=np.ones(12)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [123]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
o=np.ones((3,2))
o.ndim
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
o.ndim

2

## np.empty : this create an empty array. the elements of an empty array are random and depend on state of the memory .The resone to udr empty over zeros 
##  is speed -just make  sure to fill every elements afterwards

In [3]:
import numpy as np
sd=np.empty((6,3))
sd

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.33511290e-306, 6.23058368e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 1.78018811e-306, 1.33511562e-306],
       [1.69118515e-306, 9.34607074e-307, 2.56765117e-312]])

In [5]:
sd=np.empty(3)

In [6]:
sd

array([1.35022992e-311, 0.00000000e+000, 4.94065646e-324])

# np.arange(start,stop,step): create an array within a range'

In [132]:
x=np.arange(3,10,2) # start stop step
x

array([3, 5, 7, 9])

In [134]:
s=np.arange(2,10) # start , stop
s

array([2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
d=np.arange(4,10)
d

array([4, 5, 6, 7, 8, 9])

# np.linspace (start,stop,num): create an array with values that are space linearly  in a specified interval

In [43]:
new=np.linspace(1,6,5)
new

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [46]:
n=np.linspace(1,10,5)
n

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [4]:
import numpy as np
g=np.linspace(1,10,2)

In [5]:
g

array([ 1., 10.])

# broad casting
### Broad casting is a mechanism that allows Numpy to perform operations on array of different Shapes.
### There are many Broad casting rules , which you can learn from the numpy documentaion

#### string add str data type only 
#### int add int data type only

In [7]:
a=np.array([[1,2,3],[3,2,1]])
z='mohit' ### NO work on int data type 
s=a+z
s

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U5')) -> None

In [9]:
a=np.array([[1,2,3],[3,2,1]])
z=12 # value multiply whol array
s=a*z
s.dtype
s

array([[12, 24, 36],
       [36, 24, 12]])

In [47]:
import numpy as np
list1=np.array(1)
a=20
neg_list=list1-a
neg_list

np.int64(-19)

In [48]:
import numpy as np # to set can not add in array
set1=np.array({1,2,3,4,5})
import numpy as nw
set2=nw.array({6,7,8,9,10})
set3=set1+set2    
print(set3)

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [71]:
import numpy as np
a=np.array(['mohit','nyc','as','london']) # str add in string (data type).
s='hello' 
d=a+s
d

array(['mohithello', 'nychello', 'ashello', 'londonhello'], dtype='<U11')

In [72]:
a

array(['mohit', 'nyc', 'as', 'london'], dtype='<U6')

In [67]:
import numpy as np
a=np.array([1,2,3,4])
s=12
d=a-s
d

array([-11, -10,  -9,  -8])

In [96]:
distance=np.array([1,2,3,4,5])
s=np.array(23)
distance+s

array([24, 25, 26, 27, 28])

In [4]:
import numpy as np
g=np.array([2,4,1,3,4,3,3,3,7,8])
g.sort()
g

array([1, 2, 3, 3, 3, 3, 4, 4, 7, 8])

In [97]:
distance.shape

(5,)

In [98]:
s.shape

()

In [99]:
s.ndim

0

In [100]:
distance.ndim

1

### np.Sort () int squencs type and string alphabet order type

In [57]:
import numpy as np
w=np.array([[1,2,3,5,4],[8,7,6,9,10],[11,12,13,14,15,]])
w.sort() # int convert int(squence)
w

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [3]:
w

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
s=np.array([)
s

array([[1],
       [1]])

In [7]:
new=np.array([[1,2,5,4,6,3],[7,8,9,11,10,12]])
new.sort()
new

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
str1=np.array(['uttarakhand',1,2,3,4,'mohit','sort','almora','bagwalipokhar'])
str1.sort() # alphabat sequence type
print(str1)
str1[2:3]

['1' '2' '3' '4' 'almora' 'bagwalipokhar' 'mohit' 'sort' 'uttarakhand']

array(['3'], dtype='<U21')

## sum() add array for result

In [35]:
import numpy as np
array=np.array([[1,2,3,4,5,5],[1,2,3,4,52,3]])
array.sum()

np.int64(85)

In [2]:
from functools import reduce
import numpy as np
asd=np.array(['mohit boura','hello'])
asd.reduce()

AttributeError: 'numpy.ndarray' object has no attribute 'reduce'

In [65]:
a=np.array([1,2,3,4,5])
a.sum()

np.int64(15)

In [17]:
s=np.array([[1,2,3,4,5,6,7]])
s.sum(axis=1)

array([28])

# np.concatenate

Axis=0 direction (down) (row)
|
|
|
|
|
|
|
Axis= 1 direction (across) (column)---------------->

In [8]:
set1=np.array([1,2,3,5])
set2=np.array([1,2,3,4,5])
np.concatenate((set1,set2),axis=0)

array([1, 2, 3, 5, 1, 2, 3, 4, 5])

In [9]:
s=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
np.concatenate((s,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.concatenate((s,d),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
np.concatenate((s,d),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [20]:
don=np.array([[1,2,3,4],[5,6,7,8]])
don1=np.array([[22,2,2,2,],[1,2,3,5]])
d=np.array([[1,2,3,4],[1,2,3,4]])
j=np.concatenate((don,don1,d),axis=1)
j.reshape(2,12)

array([[ 1,  2,  3,  4, 22,  2,  2,  2,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  1,  2,  3,  5,  1,  2,  3,  4]])

In [44]:
j.shape

(2, 12)

In [45]:
j.size

24

In [46]:
j.dtype

dtype('int64')

In [42]:
g=np.array([1,2,3,4,5])
h=np.array([1,2,3,4,5])
np.concatenate((g,h),axis=0)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [12]:
n=np.array([['mohit' 'boura'],['nyc']])
len(n)

2

## . max return the maximun value of the array

In [33]:
import numpy as np
a=np.array([1,2,3,5,566,7,7777])
c=np.ones(3)
c
a.max()

np.int64(7777)

In [20]:
s=np.array([[[1,2,3*13,4],[1,3,4,5]]])
s.min()

np.int64(1)

In [105]:
s=np.array(['mohit boura','uk'])
s.max(len(s))

AxisError: axis 2 is out of bounds for array of dimension 1

## Basic Array operation
### the section covers addition , subtraction ,multiplication , divison ,and more

In [59]:
d=np.array([1,2,3,454])
s=np.array([23,4,3,4])

In [60]:
d+s

array([ 24,   6,   6, 458])

In [61]:
d-s

array([-22,  -2,   0, 450])

In [63]:
s*d

array([  23,    8,    9, 1816])

## sum

In [4]:
import numpy  as np
n=np.array([[1,3],
           [2,2]])
n.sum(axis=1)

array([4, 4])

In [82]:
n=np.array([[1,2,3,4],
            [2,3,4,5]])
n.sum(axis=1)

array([10, 14])

# reshaping an array
### arr.reshape()
## using arr.reshape() will give a new shape to an array without changing the data . just remember that when you use the reshape method ,
## the array you want to produce needs to have the same number of elements as the original array. if you start with an arrY WITH 12 ELEMENT , you all need to make 
## sure that you new array also has a total of 12 elements.

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a=np.zeros(10)
a.reshape(1,2,5)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
a.ndim

1

In [17]:
f= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
f.reshape(1,2,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

### ndexing using conditions in arrays

In [3]:
import numpy as np
fix=np.array([1,2,3,4,5,6,7,8])
fix[(fix%2==0) & (fix>2)]

array([4, 6, 8])

In [6]:
f=np.array([1,2,3,4])
f[(f%2!=0) | (f<2)]

array([1, 3])

In [9]:
f=np.array([[1,2,3,4],[5,6,7,8]])
f[(f%2==0)]

array([2, 4, 6, 8])

# sum

In [32]:
import  numpy as np
nh=np.array([[1,2,4,4,5],[1,2,3,4,5]])
nh.sum()

np.int64(31)

In [22]:
n=np.array([[1,2,3,4],
            [1,2,3,4]])
n.sum(axis=0)

array([2, 4, 6, 8])

In [16]:
h=np.array([[1,2,3,4]
            ,[5,6,7,8]])
h.sum(axis=1)

array([10, 26])

In [17]:
h.sum(axis=0)

array([ 6,  8, 10, 12])

In [18]:
nf=np.arange(10)
nf[nf%2==0]

array([0, 2, 4, 6, 8])

In [41]:
nf.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
f=np.ones(6)
f

array([1., 1., 1., 1., 1., 1.])

In [29]:
f.reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
f.reshape(3,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
a[(a%2==0)& (a>2)]

array([4, 6, 8])

In [30]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a[a<2]

array([1])

In [31]:
a[(a>2) & (a%2==0)]

array([4, 6])

In [27]:
import numpy as np
a=np.array([1,2,3,5,4])
a.sort()
a

array([1, 2, 3, 4, 5])

In [35]:
ak=np.array([1,2,3,4,5])
ak[(ak%2==0) | (ak<2)]

array([1, 2, 4])

In [4]:
import numpy as np
zero_x=np.zeros((3,4))   # 3 rows, 4columns
zero_x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
zero_x.ndim

2

In [9]:
import numpy as np    
import pandas as pd
own=np.ones((2,4))
hola=pd.DataFrame(own)       
hola

     0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0

# FULL Array ( custom value)

In [11]:
import numpy as pd
import pandas as pd
ott=np.full((2,3), 5)   #  2 rows , 3 columns  and fullfill by 5
ott

array([[5, 5, 5],
       [5, 5, 5]])

In [12]:
gl=pd.DataFrame(ott)
gl

   0  1  2
0  5  5  5
1  5  5  5

In [14]:
gl.ndim

2

In [16]:
gl[:3]

   0  1  2
0  5  5  5
1  5  5  5

In [18]:
import numpy as np
hu=np.arange(1,10,2)
hu

array([1, 3, 5, 7, 9])

In [27]:
To_say_hi=pd.Series((hu),index=[1,2,3,4,5])
To_say_hi

1    1
2    3
3    5
4    7
5    9
dtype: int64

# identity Matrix (eye)

In [41]:
cluth=np.eye(0,6)
cluth

array([], shape=(0, 6), dtype=float64)

 cluth=np.eye(3,7,5)  

- 7 → columns

 - 5 → diagonal shift (k = 5)
cluth3 → rows

- 7 → columns

 - 5 → diagonal shift (k = 5)

In [53]:
cluth =np.eye(3,7,5)# row , columns and diagonal shift after 5 columns add one 1 and every row + 1 in diagonal
cluth

array([[0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [55]:
g=np.eye(4,5,1)
g

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
h=np.eye(10,5,0)
h

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
arr=np.array([1,2,3],dtype=float)
arr

array([1., 2., 3.])

In [57]:
print (type(arr))

<class 'numpy.ndarray'>

# flatten (convert To 1D)

In [7]:
import numpy as np
f=np.ones((5,7))
f

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
f.ndim

2

In [9]:
import pandas as pd
w=pd.DataFrame(f)
w

     0    1    2    3    4    5    6
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [14]:
flat =f.flatten()   # any variable convert anyD  to 1D
flat

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [15]:
import pandas as pd
e=pd.Series(flat)
e

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
dtype: float64

In [16]:
flat.ndim

1

In [20]:
flat.min()

np.float64(1.0)

In [22]:
flat.mean(   # avg
)

np.float64(1.0)

In [23]:
flat.max()

np.float64(1.0)