# Creating a Pandas Series

### 🔹 Pandas Series
## ***1-dimensional data structure***
### ***Similar to a single column in Excel or a list with labels***
### ***Can hold one data type at a time***
### ***Has an index***

In [2]:
import pandas as pd
ht=pd.Series()
ht

Series([], dtype: object)

In [3]:
import pandas as pd
import numpy as np
ser1=pd.Series(np.array(['M','u','k','h','a','n','i']))
ser1

0    M
1    u
2    k
3    h
4    a
5    n
6    i
dtype: object

In [6]:
ser1[2]

'k'

In [7]:
import pandas as pd
import numpy as np
ser1=pd.Series(np.array(['M','u','k','h','a','n','i']),
              index=['a','b','c','d','e','f','g'])
ser1

a    M
b    u
c    k
d    h
e    a
f    n
g    i
dtype: object

In [8]:
import pandas as pd
ser2=pd.Series(['put','a','dent','in','the','universe'])
ser2

0         put
1           a
2        dent
3          in
4         the
5    universe
dtype: object

In [ ]:
import pandas as pd
ser3=pd.Series({'Elon Musk':'Enterpreneur','Albert Einstein':'Physicist','APJ Abul kalam':'Missile Men if India'})
ser3

In [ ]:
ser3['Elon Musk']

In [6]:
import  numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
import pandas as pd
ser4 =pd.Series(np.arange(1,10,2))
ser4

0    1
1    3
2    5
3    7
4    9
dtype: int64

# Accessing elements of a pandas Series

In [5]:
import pandas as pd
df=pd.DataFrame({'Name':['Mohit','Paras','neeraj'],
                "Marks":[67,44,66]})
df

     Name  Marks
0   Mohit     67
1   Paras     44
2  neeraj     66

In [6]:
df=pd.DataFrame({'Name':['Mohit','Paras','neeraj'],
                "Marks":[67,44,78]},index=[1,2,3])
df

     Name  Marks
1   Mohit     67
2   Paras     44
3  neeraj     78

In [7]:
df['Name']

1     Mohit
2     Paras
3    neeraj
Name: Name, dtype: object

In [8]:
df['Marks']

1    67
2    44
3    78
Name: Marks, dtype: int64

In [9]:
type(df['Name'])

pandas.core.series.Series

In [10]:
type(df['Marks'])

pandas.core.series.Series

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df['Marks'].dtype

dtype('int64')

In [13]:
df["Name"].dtype

dtype('O')

In [14]:
import pandas as pd
import numpy as np
elon_ai_comp=np.array(['Tesla','Starlink','X','Solarcity','xAI'])
ser=pd.Series(elon_ai_comp,index=['a','b','c','d','e'])
ser

a        Tesla
b     Starlink
c            X
d    Solarcity
e          xAI
dtype: object

In [16]:
ser['a']

'Tesla'

In [18]:
ser[['a','b','c']] #accessing multiple elements

a       Tesla
b    Starlink
c           X
dtype: object

In [19]:
ser['a':'d']

a        Tesla
b     Starlink
c            X
d    Solarcity
dtype: object

In [21]:
ser['a':'e':2] # start , stop, step

a    Tesla
c        X
e      xAI
dtype: object

# Operations in Pandas series

In [22]:
import pandas as pd
s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([1,2,3],index=['a','b','c'])
result=s1+s2
result

a    11
b    22
c    33
dtype: int64

In [23]:
import pandas as pd
s1=pd.Series([10,20,30],index=['a','b','c'])  # add same index 
s2=pd.Series([1,2,3],index=['a','b','f'])
result=s1+s2
result

a    11.0
b    22.0
c     NaN
f     NaN
dtype: float64

In [27]:
import pandas as pd
s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([1,2,3],index=['u','b','f'])
result=s1+s2
result

a     NaN
b    22.0
c     NaN
f     NaN
u     NaN
dtype: float64

In [28]:
# comparsion
s1=pd.Series([10,20,30])
s2=pd.Series([10,23,30])
# comparing the two Series
re=s1==s2
re

0     True
1    False
2     True
dtype: bool

In [29]:
s1[s1==s2]

0    10
2    30
dtype: int64

In [31]:
s1[(s1>5)&(s2>20)]

1    20
2    30
dtype: int64

In [33]:
# Pandas Series Index Attribute
import pandas as pd
data=pd.Series([10,20,30,40],index=['a','b','c','d'])
# Accessing the index 
print('modified series:\n',data.index)

modified series:
 Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
# modifying the index 
data.index =['w','x','y','z']
print('Modified Series:\n',data)

Modified Series:
 w    10
x    20
y    30
z    40
dtype: int64

In [40]:
# Assinging Duplicate index labels
import pandas as pd
import numpy as np
elon_ai_comp=np.array(['Tesla','Starlink','X','Solarcity','xAI'])
ser=pd.Series(elon_ai_comp)
ser.index=['a','a','c','d','e']
ser

a        Tesla
a     Starlink
c            X
d    Solarcity
e          xAI
dtype: object

In [41]:
ser['a']

a       Tesla
a    Starlink
dtype: object

In [43]:
ser.iloc[0]

'Tesla'

# Resetting Series index

In [44]:
ser.reset_index()

  index          0
0     a      Tesla
1     a   Starlink
2     c          X
3     d  Solarcity
4     e        xAI

In [45]:
ser.reset_index (drop=True)

0        Tesla
1     Starlink
2            X
3    Solarcity
4          xAI
dtype: object

In [46]:
ser

a        Tesla
a     Starlink
c            X
d    Solarcity
e          xAI
dtype: object

In [47]:
# So use inplace =True
ser.reset_index(drop=True,inplace=True)

In [48]:
ser

0        Tesla
1     Starlink
2            X
3    Solarcity
4          xAI
dtype: object