# Scikit Learn
## Learning Model Building in Scikit-learn.
### Scikit-learn  is an open-source Python library that simplifies the process of building machine learning models. 
### It offers a clean  and consistent interface that helps both beginners and experienced users work efficiently.
### . Supports tasks like classification, regression , clustering and preprocessing
### .  Makes model building fast and reliable
### . provides ready - to-use tools for traning and evaluvation
### . reduces completely by avoiding manual implementation of algorithms

# step1: Loading a Dataset
### A dataset consis of: 
### Features (x) : input variables that describe the data
### Target (y) : The value we want to predict
### Scikit-learn provides built-in-datasets like lries,Digits and Boston Housing.Using the iris dataset:
### load_iris() loads the data
### X stores feature data
### y storres target labels
### feature_names and target_names give descriptives names
### We can inspest the first rows to understand the structure .For custom datasets ,Pandas is commmonly used to load external files such as CSV.

In [3]:
from sklearn.datasets import load_iris
iris =load_iris()
X=iris.data
y=iris.target
feature_names =iris.feature_names
target_names=iris.target_names

print('Feature names:',feature_names)
print('target  names:',target_names)
print('\nType of x is:',type(X))
print('\nFirst 5 rows of x:\n',X[1:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target  names: ['setosa' 'versicolor' 'virginica']

Type of x is: <class 'numpy.ndarray'>

First 5 rows of x:
 [[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

# Step2: Splitting the Dataset
### To evaluate a model fairly , we split data into:
 - Training set: Used to train the model 
-  Testing set: Used to evaluate how well the model generalizes-
- using Tran_test_split we split the iris dataset so that 60% is for traning (test_size=0.4).random_state=1 ensures repoducibility.
  ## After splitting, we get
- X_train,y_train->Traning data
-   X_test,y_test-> Testing data
-   Chaecking the shapes ensures the data is split correctly.

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=1
)

In [5]:
print('x_train shape:', X_train.shape)
print('X_test  shape:',X_test.shape)
print('y_train shape:',y_train.shape)
print('y_test shape;',y_test.shape)

x_train shape: (90, 4)
X_test  shape: (60, 4)
y_train shape: (90,)
y_test shape; (60,)

In [6]:
print(X) # 150rows and 4 columns

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

In [7]:
import pandas as pd
df=pd.DataFrame(X)        # convert it into a dataframe use pandas library 
df

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [8]:
df.describe()

                0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

Step 3: Handling Categorical Data
Machine learning algorithms work with numerical inputs, so categorical (text) data must be converted into numbers. If not encoded properly, models can misinterpret
categories. Scikit-learn provides multiple encoding methods:

 - 1. Label Encoding:

It converts each category into a unique integer. For example in a column with categories like 'cat', 'dog' and 'bird", it would convert them to 0, 1 and 2 respectively. This
method works well when the categories have a meaningful order such as "Low", "Medium" and "High".

LabelEncoder0: It is initialized to create an encoder object that will convert categorical values into numerical labels.

fit.transform0: This method first fits the encoder to the categorical data and then transforms the categories into corresponding numeric lables.

In [9]:
from sklearn.preprocessing import LabelEncoder

categorical_feature = ['low', 'medium','high']

encoder = LabelEncoder()

encoded_feature = encoder.fit_transform(categorical_feature)

print("Encoded featura:", encoded_feature)

Encoded featura: [1 2 0]

In [10]:
from sklearn.preprocessing import LabelEncoder

categorical_feature = ['mohit', 'abhay ','high']

encoder = LabelEncoder()

encoded_feature = encoder.fit_transform(categorical_feature)

print("Encoded featura:", encoded_feature)

Encoded featura: [2 0 1]

In [11]:
from sklearn.preprocessing import LabelEncoder

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird']    # categorical convert to numerical by alphabat  postion
                                                            
encoder = LabelEncoder()

encoded_feature = encoder.fit_transform(categorical_feature)

print("Encoded featura:", encoded_feature)

Encoded featura: [1 2 2 1 0]

 * 2. One-Hot Encoding:

One-Hot Encoding creates separate binary columns for each category. This is useful when categories do not have any natural

ordering. Example: cat, dog, bird-> 3 new columns (cat/dog/bird) with 1s and Os.
Input must be reshaped into a 2D array

OneHotEncoder(sparse_output=False) generates binary columns

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird',]

categorical_feature = np.array(categorical_feature)  # ValueError: Expected 2D array, got 1D array instead:
array=['cat' 'dog' 'dog' 'cat' 'bird']
#   Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample

encoder = OneHotEncoder(sparse_output=False)

encoded_feature = encoder.fit_transform(categorical_feature)

print("OneHotEncoded feature:\n", encoded_feature)

SyntaxError: invalid syntax (2312247805.py, line 7)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird',]

categorical_feature = np.array(categorical_feature) .reshape(-1,1)

print(categorical_feature)

encoder = OneHotEncoder(sparse_output=False)  # fit_teransfrom is only use in 2D

encoded_feature = encoder.fit_transform(categorical_feature)

print("OneHotEncoded feature:\n", encoded_feature)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird',]

categorical_feature = np.array(categorical_feature) .reshape(1,-1)

print(categorical_feature)

encoder = OneHotEncoder(sparse_output=False)

encoded_feature = encoder.fit_transform(categorical_feature)

print("OneHotEncoded feature:\n", encoded_feature)

In [ ]:
import numpy as np

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird',]

categorical_feature = np.array(categorical_feature).reshape(5 ,1)                                                
                                                           
categorical_feature

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

categorical_feature = ['cat']

categorical_feature = np.array(categorical_feature) .reshape(-1,1)

print(categorical_feature)

encoder = OneHotEncoder(sparse_output=False)

encoded_feature = encoder.fit_transform(categorical_feature)

print("OneHotEncoded feature:\n", encoded_feature)

***What does sparse_output=True do? (default)*** 
**oneHotEncoder(sparse_outPut=True)**
- Output type : Sparse matrix
- Memory efficient
- Hard to read (for humans)
- not Numpy array
- scipy spars matrix
- 
  **use in:**
  - Large dataseta
- High-cardinality categorical features
- Production systems
  ***what does sparse_output=False do?***
**onehotencoder(spase_ouptput=False)**
  - output type: Dense Numpy array
  - easy to visualize
  - Beginner - friendly
  - User more memory
**example output:**

array([1.,0.,0.],
      [0.,1.,0.],
      [0.,0.,1.]
    ])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird',]

categorical_feature = np.array(categorical_feature) .reshape(-1,1)

print(categorical_feature)

encoder = OneHotEncoder(sparse_output=True)

encoded_feature = encoder.fit_transform(categorical_feature)

print("OneHotEncoded feature:\n", encoded_feature)
print(type(encoded_feature))

- Step 4: Training the Model
- Now that our data is ready, it's time to train a machine leaming model. Scikit-leam has many algorithms with a consistent interface for training,prediction and evaluation. Here we'll use Logistic Regression as an example.
- Note: We will not go into the details of how the algorithm works as we are interested in understanding its implementation only.
- log.reg = LogisticRegression(max_jter=200): Creating a logistic regression classifier object.
- log_reg.fit().train.y_train): Using this the logistic regression model adjusts the model's parameters to best fit the data.

In [14]:
from sklearn.linear_model import LogisticRegression  # to train the algorithms
log_reg =LogisticRegression(max_iter=200)
log_reg.fit(X_train,y_train)

LogisticRegression(max_iter=200)

***Step 5: Make Predication***
- once trained we use the model to make predication on the test data X_test by calling the predict method.This returns predicted labels y_pred.
- log_reg.predict It uses trained logistic regression model  to predict lables for the data X_test.

In [15]:
y_pred=log_reg.predict(X_test)

***step: Evaluating Model Accuracy***
- Check how well our model is performing by compering y_test and Y_pred . Here we are metrics module's method  accuracy_score.

In [16]:
from sklearn import metrics
print ('Logistic Regression model accuracy:',metrics.accuracy_score(y_test,y_pred))

Logistic Regression model accuracy: 0.9666666666666667

- Now we want our model to make predictions on new sample data. Then the simple input can simply be passed in the samee way as we pass any feature matrix .Here we used it as sample=[[3,5,4,2],[2,3,5,4]]

In [17]:
sample=[[3,5,4,2],[2,3,5,4]]
preds=log_reg.predict(sample)
pred_species=[iris.target_names[p]for p in preds]
print('Predictions:',pred_species)

Predictions: [np.str_('virginica'), np.str_('virginica')]

***prosessing Data vs processed Data***
- processing data definition involes defining and menaging the structure  characteristics  and specification of data within an organization.
- Processed data defination typically refres to the refined and finalized specification and attributes associated with data after it has undergone various processing steps.
- Data processing process involes a series involes a series of stages to transfrom raw data into meaningful information. here the six fundamental stages of data  processing process.

***1. collection*** 

- The process begins with the collection of raw data from various sources. The stage establishes the foundation for subsequent processing, ensuring a comprehensive pool of
data relevant to the intended analysis. It could include surveys, sensors, databases, or any other means of gathering relevant information.

***2. Preparation***

- Data preparation focuses on organizing, data cleaning, and formatting raw data. Irrelevant information is filtered out, errors are corrected, and the data is structured in a waythat facilitates efficient analysis during subsequent stages of processing.

***3. Input***

- During the data input stage, the prepared data is entered into a computer system. This can be achieved through manual entry or automated methods, depending on the nature of the data and the systems in place.

***4.Data Processing***

- The core of data processing involves manipulating and analyzing the prepared data. Operations such as sorting, summarizing, calculating, and aggregating are performed to extract meaningful insights and  patterns.

***5. Data Output***
- The  results of data processing are presented in a comprehensible format during the data output stage. This could include reports, charts, graphs, or other visual representation that facilitate understading and decision-making based on the analyzed data



***6. Data Storage***

- The final stage entails storing the processed data for future reference and analysis. This is crucial for maintaining a historical record, enabling efficient retrieval, and supporting ongoing or future data-related initiatives. Proper data storage ensures the longevity and accessibility of valuable information.